version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: 'Save text to file'
          command: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - .

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: 'Trying to print text from the filename'
          command: cat output.txt

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
