version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: 'Say Hello'
          command: 'echo Hello,'

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Save text to file",
          command: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Trying to print text from the file"
          command: cat output.txt
  

workflows:
  welcome:
    jobs:
      # - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_my_name
